# Generated by Django 3.0.7 on 2020-06-17 11:24
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from django.db import migrations, models


def delete_question_draft_objects_with_invalid_url(apps, schema_editor):
    question_draft_model = apps.get_model('processor', 'questiondraft')

    pks_to_delete = []
    validate_url = URLValidator()
    for item in question_draft_model.objects.all():
        try:
            validate_url(item.source)
        except ValidationError:
            pks_to_delete.append(item.pk)

    question_draft_model.objects.filter(pk__in=pks_to_delete).delete()


def migrate_chatbot_drafts_to_news_draft(apps, schema_editor):
    question_draft_model = apps.get_model('processor', 'questiondraft')
    news_draft_model = apps.get_model('processor', 'newsdraft')

    news_draft_objects_to_create = [
        news_draft_model(
            url=item.source,
            comment=item.question,
            text="",
            screenshot_url="",
            reporter_email=item.reporter_email,
            reported_at=item.reported_at,
            origin="chatbot",
        )
        for item in question_draft_model.objects.all()
    ]

    news_draft_model.objects.bulk_create(news_draft_objects_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_questiondraft'),
    ]

    operations = [
        migrations.RunPython(delete_question_draft_objects_with_invalid_url),
        migrations.AddField(
            model_name='newsdraft',
            name='origin',
            field=models.CharField(
                choices=[
                    ('plugin', 'Plugin'), ('chatbot', 'Chatbot'), ('mobile', 'Mobile')
                ],
                default='plugin',
                max_length=30,
            ),
        ),
        migrations.RunPython(migrate_chatbot_drafts_to_news_draft),
        migrations.DeleteModel(
            name='QuestionDraft',
        ),
    ]
